### ISSUE TITLE
Docker build errors in Cmake

### ISSUE THREAD

**Issue by stdavids** [The-OpenROAD-Project/OpenROAD-flow#16]
When attempting to build the tools with docker by running `$ docker build -t openroad -f ./OpenROAD/Dockerfile ./OpenROAD` the build errors out during the `cmake` process. Attached is the output log.

Appears to be different than #12 

[build.log](https://github.com/The-OpenROAD-Project/OpenROAD-flow/files/4032643/build.log)

**Comment by rovinski** [comment]
Hi @stdavids,

Was this issue encountered when using the latest version of the build Makefile? If not, try re-cloning using the build makefile.

This issue is caused because `git clone --recursive` for some reason does not seem to recurse more than 1 level deep in the submodule hierarchy. You need to `cd` into each of the directories that cause errors and do `git submodule update --init --recursive`
